# Buid BulletSim binaries from the latest Bullet and BulletSim glue sources

name: BulletSim binaries

on:
  push:
    branches: 
      - dotnet6

jobs:
  build:
    strategy:
      matrix: 
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-20.04
            ext: so
          - os: macos-12
            ext: dylib

    runs-on: ${{ matrix.os }}

    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          ref: dotnet6
          path: bulletsim

      - name: checkout Bullet
        uses: actions/checkout@v3
        with:
          repository: bulletphysics/bullet3
          path: bulletsim
          clean: false
#        run: |
#          cd bulletsim
#          git clone --depth=1 https://github.com/bulletphysics/bullet3.git

      - name: apply patches to Bullet
        run: |
          cd bulletsim/bullet3
          for file in ../00*.patch ; do cat $file | patch -p1 ; done

      - name: build Bullet physics engine
        run: |
          cd bulletsim
          BULLETDIR=bullet3 ./buildBulletCMake.sh

      - name: build BulletSim
        run: |
          cd bulletsim
          ./buildBulletSim.sh

      - name: Upload built image
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.os }}
          path: bulletsim/*.${{ matrix.ext }}
          if-no-files-found: error

# vim: tabstop=2 shiftwidth=2 autoindent expandtab

