# Buid BulletSim binaries from the latest Bullet and BulletSim glue sources

name: BulletSim binaries

env:
  branch: dotnet6

on:
  push:
    branches: 
      - ${{ branch }}

jobs:
  build:
    strategy:
      options:
        - os: ubuntu-latest
          codecov: false
        - os: macos-latest
          codecov: false
        - os: windows-latest
          codecov: false

    runs-on: ${{ matrix.options.os }}

    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ branch }}
          path: bulletsim

      - name: download Bullet
        run: |
          cd bulletsim
          git clone https://github.com/bulletphysics/bullet3.git

      - name: build Bullet physics engine
        run: |
          cd bulletsim
          BULLETDIR=bullet3 ./buildBulletCMake.sh

      - name: build BulletSim
        run: |
          cd bulletsim
          ./buildBulletSim.sh

# vim: tabstop=2 shiftwidth=2 autoindent expandtab

